### ISSUE TITLE
[Android] Build failed with cordova-plugin-androidx-adapter

### ISSUE THREAD

**Issue by xyangwang** [dpa99c/cordova-plugin-androidx-adapter#15]
In other plugin uses `android.support.v7.widget.GridLayoutManager` class, when I run `ionic cordova build android`, I got failed result.

In `class-mappings.json` file, `android.support.v7.widget.GridLayoutManager` convert to `androidx.recyclerview.widget.GridLayoutManager`, but in my java file it is converted to `androidx.gridlayout.widget.GridLayoutManager`.

It should covert  `android.support.v7.widget.GridLayoutManager` before `android.support.v7.widget.GridLayout`.

```
"android.support.v7.widget.GridLayout": "androidx.gridlayout.widget.GridLayout",
"android.support.v7.widget.GridLayoutManager": "androidx.recyclerview.widget.GridLayoutManager",
```

**Comment by dpa99c** [comment]
Fix published in v1.1.3 - please give that a try and let me know if you still have issues
