### ISSUE TITLE
Could not find any version that matches androidx.legacy:legacy-support-v4:27.+.

### ISSUE THREAD

**Issue by GaryMeliman** [dpa99c/cordova-plugin-androidx-adapter#3]
_Hi im getting the following error after installing this plugin.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find any version that matches androidx.legacy:legacy-support-v4:27.+.
     Versions that do not match:
       - 1.0.0
       - 1.0.0-rc02
       - 1.0.0-rc01
       - 1.0.0-beta01
       - 1.0.0-alpha3
       - + 1 more
     Required by:
         project :app
   > Could not find any version that matches androidx.legacy:legacy-support-v4:27.+.
     Versions that do not match:
       - 1.0.0
       - 1.0.0-rc02
       - 1.0.0-rc01
       - 1.0.0-beta01
       - 1.0.0-alpha3
       - + 1 more
     Required by:
         project :app
   > Could not find any version that matches androidx.appcompat:appcompat:27.+.
     Versions that do not match:
       - 1.1.0-beta01
       - 1.1.0-alpha05
       - 1.1.0-alpha04
       - 1.1.0-alpha03
       - 1.1.0-alpha02
       - + 9 more
     Required by:
         project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights._

**Comment by dpa99c** [comment]
Did you also install `cordova-plugin-androidx`?

Please try [this test scenario](https://github.com/arnesson/cordova-plugin-firebase/issues/1081#issuecomment-503135862).

**Comment by GaryMeliman** [comment]
> Did you also install `cordova-plugin-androidx`?
> 
> Please try [this test scenario](https://github.com/arnesson/cordova-plugin-firebase/issues/1081#issuecomment-503135862).

Yes, i runned this commands.
ionic cordova platform add android@8.0.0
ionic cordova plugin add cordova-plugin-androidx
ionic cordova plugin add cordova-plugin-androidx-adapter
ionic cordova run android

**Comment by edgarnsr** [comment]
Same here. When I add onesginal cordova plugin and cordova androidx and cordova androidx-adapter give me this error:
Could not find any version that matches androidx.legacy:legacy-support-v4:28.+.
Could not find any version that matches androidx.annotation:annotation:28.+.

**Comment by dpa99c** [comment]
Could you list all the plugins in a project which this issue occurs in?
I'm looking for conditions to reproduce it.

**Comment by GaryMeliman** [comment]
Sure.
Here it is.
ionic cordova plugin list
> cordova.cmd plugin ls
com-sarriaroman-photoviewer 1.2.2 "PhotoViewer"
cordova-fabric-plugin 1.1.14-dev "cordova-fabric-plugin"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.0.2 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appcenter-crashes 0.3.4 "App Center Crashes for Cordova"
cordova-plugin-appcenter-shared 0.3.4 "App Center shared code for Cordova"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-downloadmanager 0.0.1 "DownloadManager"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-filepath 1.5.1 "cordova-plugin-filepath"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic 5.2.7 "cordova-plugin-ionic"
cordova-plugin-ionic-webview 2.4.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-media-capture 3.0.2 "Capture"
cordova-plugin-nativegeocoder 3.2.2 "NativeGeocoder"
cordova-plugin-request-location-accuracy 2.2.3 "Request Location Accuracy"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
cordova-support-google-services 1.3.1 "cordova-support-google-services"
cordova.plugins.diagnostic 4.0.10 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.7 "OneSignal Push Notifications"

**Comment by edgarnsr** [comment]
Here it is:

> call-number 0.0.2 "Cordova Call Number Plugin"
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.0.2 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-disable-ios11-statusbar 1.0.0 "cordova-plugin-disable-ios11-statusbar"
cordova-plugin-facebook4 1.7.4 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geofence 0.6.0 "geofence"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-inappbrowser-wkwebview 1.0.7 "InAppBrowser (WKWebView)"
cordova-plugin-ionic-webview 4.1.0 "cordova-plugin-ionic-webview"
cordova-plugin-listpicker 2.2.2 "ListPicker"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-mauron85-background-geolocation 3.0.1 "CDVBackgroundGeolocation"
cordova-plugin-network-information 1.3.4 "Network Information"
cordova-plugin-safariviewcontroller 1.6.0 "SafariViewController"
cordova-plugin-secure-storage 2.6.8 "SecureStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-taptic-engine 2.1.0 "Taptic Engine"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
cordova-wheel-selector-plugin 1.0.0 "Cordova Wheel Selector Plugin"
cordova.plugins.diagnostic 3.9.2 "Diagnostic"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.4.7 "OneSignal Push Notifications"
phonegap-plugin-barcodescanner 8.0.1 "BarcodeScanner"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"

**Comment by dpa99c** [comment]
OK thanks, there's a lot of potential plugins to conflict there!
I'll have a look at this when I get a mo.

**Comment by GaryMeliman** [comment]
Finally made i it work.
I just had to change some depenencies in project.properties.
I changed

target=android-28
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=com-sarriaroman-photoviewer/gestion-photoviewer.gradle
cordova.gradle.include.2=cordova-fabric-plugin/gestion-build-extras.gradle
cordova.system.library.1=com.microsoft.appcenter:appcenter:2.0.0
cordova.system.library.2=com.microsoft.appcenter:appcenter-crashes:2.0.0
cordova.gradle.include.3=cordova-plugin-badge/gestion-badge.gradle
cordova.system.library.3=com.android.support:support-v4:24.1.1+
cordova.gradle.include.4=cordova-plugin-firebase/gestion-build.gradle
cordova.system.library.4=com.google.android.gms:play-services-tagmanager:+
cordova.system.library.5=com.google.firebase:firebase-core:+
cordova.system.library.6=com.google.firebase:firebase-messaging:+
cordova.system.library.7=com.google.firebase:firebase-config:+
cordova.system.library.8=com.google.firebase:firebase-perf:+
cordova.system.library.9=com.android.support:support-annotations:27.+
cordova.system.library.10=com.android.support:support-v4:26.+
cordova.gradle.include.5=cordova-plugin-local-notification/gestion-localnotification.gradle
cordova.system.library.11=com.google.android.gms:play-services-location:15.+
cordova.gradle.include.6=cordova-support-google-services/gestion-build.gradle
cordova.system.library.12=com.android.support:support-v4:26.+
cordova.system.library.13=com.android.support:appcompat-v7:26.+
cordova.system.library.14=com.onesignal:OneSignal:3.10.8
cordova.gradle.include.7=onesignal-cordova-plugin/gestion-build-extras-onesignal.gradle

To 

target=android-28
android.library.reference.1=CordovaLib
android.library.reference.2=app
cordova.gradle.include.1=com-sarriaroman-photoviewer/gestion-photoviewer.gradle
cordova.gradle.include.2=cordova-fabric-plugin/gestion-build-extras.gradle
cordova.system.library.1=com.microsoft.appcenter:appcenter:2.0.0
cordova.system.library.2=com.microsoft.appcenter:appcenter-crashes:2.0.0
cordova.gradle.include.3=cordova-plugin-badge/gestion-badge.gradle
// added androidx.legacy insted of com.android.support:support
cordova.system.library.3=androidx.legacy:legacy-support-v4:1.0.0
cordova.gradle.include.4=cordova-plugin-firebase/gestion-build.gradle
cordova.system.library.4=com.google.android.gms:play-services-tagmanager:+
cordova.system.library.5=com.google.firebase:firebase-core:+
cordova.system.library.6=com.google.firebase:firebase-messaging:+
cordova.system.library.7=com.google.firebase:firebase-config:+
cordova.system.library.8=com.google.firebase:firebase-perf:+
cordova.system.library.9=com.android.support:support-annotations:27.+
cordova.gradle.include.5=cordova-plugin-local-notification/gestion-localnotification.gradle
cordova.system.library.11=com.google.android.gms:play-services-location:15.+
cordova.gradle.include.6=cordova-support-google-services/gestion-build.
// added androidx.appcompat insted of com.android.support:appcompat
cordova.system.library.13=androidx.appcompat:appcompat:1.0.2
cordova.system.library.14=com.onesignal:OneSignal:3.10.8
cordova.gradle.include.7=onesignal-cordova-plugin/gestion-build-extras-onesignal.gradle

**Comment by dpa99c** [comment]
ok thanks. maybe I need to get this plugin to search/replace Android Support library package names in `project.properties` as well as `app/build.gradle` to fix this.
Will investigate.

**Comment by dpa99c** [comment]
I've just published `cordova-plugin-androidx-adapter@1.1.0` to npm which also migrates references in `project.properties` and `AndroidManifest.xml` - please give it a try as it should resolve the problems above.

**Comment by edgarnsr** [comment]
It is amazing! with the update the command "ionic cordova build android" works without manually change project.properties. thanks!
