### ISSUE TITLE
Error on building : Task :app:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by matthieup240** [dpa99c/cordova-plugin-androidx-adapter#4]
Hi, my config is : 

Ionic:
   Ionic CLI         : 5.0.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework   : ionic1 1.3.1
   @ionic/v1-toolkit : 1.0.18

Cordova:
   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 23 other plugins)

Utility:
   cordova-res : 0.3.0
   native-run  : not installed

System:
   Android SDK Tools : 26.1.1 (/Users/matthieu/Library/Android/sdk/)
   ios-deploy        : 1.9.4
   ios-sim           : 7.0.0
   NodeJS            : v11.9.0 (/usr/local/Cellar/node/11.9.0/bin/node)
   npm               : 6.5.0
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001

**The installed plugins :** 
code-push 2.0.6 "CodePushAcquisition"
cordova-android-firebase-gradle-release 3.0.0 "cordova-android-firebase-gradle-release"
cordova-android-play-services-gradle-release 3.0.0 "cordova-android-play-services-gradle-release"
cordova-android-support-gradle-release 3.0.0 "cordova-android-support-gradle-release"
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-cocoapod-supportx 1.6.1 "Cordova CocoaPods Dependency Support"
cordova-plugin-code-push 1.11.19 "CodePush"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-email 1.2.7 "EmailComposer"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-firebasex 2.1.0 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.0 "cordova-plugin-ionic-webview"
cordova-plugin-mauron85-background-geolocation 3.0.1 "CDVBackgroundGeolocation"
cordova-plugin-settings-hook 0.2.7 "Cordova Settings Hooks"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.7.2 "Toast"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova.plugins.diagnostic 5.0.0 "Diagnostic"

**And I get this error :**

> > Task :app:compileDebugJavaWithJavac FAILED
> 34 actionable tasks: 6 executed, 28 up-to-date
> /Users/Sources/platform/mobile/platforms/android/app/src/main/java/org/apache/cordova/firebase/FirebasePluginMessagingService.java:49: error: method does not override or implement a method from a supertype
>     @Override
>     ^
> /Users/Sources/platform/mobile/platforms/android/app/src/main/java/org/apache/cordova/firebase/FirebasePluginMessagingService.java:51: error: cannot find symbol
>         super.onNewToken(refreshedToken);
>              ^
>   symbol: method onNewToken(String)
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 2 errors
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 6s
> /Users/Sources/platform/mobile/platforms/android/gradlew: Command failed with exit code 1 Error output:
> /Users/Sources/platform/mobile/platforms/android/app/src/main/java/org/apache/cordova/firebase/FirebasePluginMessagingService.java:49: error: method does not override or implement a method from a supertype
>     @Override
>     ^
> /Users/Sources/platform/mobile/platforms/android/app/src/main/java/org/apache/cordova/firebase/FirebasePluginMessagingService.java:51: error: cannot find symbol
>         super.onNewToken(refreshedToken);
>              ^
>   symbol: method onNewToken(String)
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 2 errors
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:compileDebugJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 6s

I don't understand why I get this error. Thanks for your help

**Comment by dpa99c** [comment]
I suspect the cause is `cordova-android-firebase-gradle-release` which will blanket override the dependency versions specified by `cordova-plugin-firebasex` - either with the manually set version specified by `FIREBASE_VERSION` or using its default version. Please trying removing this plugin from the build. 

Also see [this comment](https://github.com/dpa99c/cordova-plugin-firebase/issues/11#issuecomment-504935119) and proceed as requested.

**Comment by kapilSoni101** [comment]
@dpa99c : sir i have got  same error but i am not using ordova-plugin-firebase i used below plugin

> cordova-plugin-fcm-with-dependecy-updated

 so tell me what i do fix?
