### ISSUE TITLE
Error: Cannot find module 'recursive-readdir'

### ISSUE THREAD

**Issue by globules-io** [dpa99c/cordova-plugin-androidx-adapter#7]
- [X ] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

Hello, not sure if I should submit here or FirebaseX. Here are my plugin

```
    <plugin name="cordova-plugin-androidx" spec="^1.0.2" />
    <plugin name="cordova-plugin-androidx-adapter" spec="^1.1.0" />
    <plugin name="cordova-plugin-firebasex" spec="^6.1.0" />
```

When adding a platform doing

`cordova platform add android@latest`

I get

`cordova-plugin-androidx-adapter: EXCEPTION: Failed to load dependencies: Error: Cannot find module recursive-readdir`

Complete log

`cordova-custom-config: Skipping auto-restore of config file backup(s)
cordova-custom-config: Applied custom config from config.xml to [app path]\platforms\android\app\src\main\AndroidManifest.xml
cordova-plugin-androidx: Updated gradle.properties to enable AndroidX
cordova-plugin-androidx-adapter: EXCEPTION: Failed to load dependencies: Error: Cannot find module 'recursive-readdir'
Preparing Firebase on Android`
`
I also tried to remove cordova-plugin-androidx from config, removed platform and only added 

```
    <plugin name="cordova-plugin-androidx" spec="^1.0.2" />
    <plugin name="cordova-plugin-firebasex" spec="^6.1.0" />
```

Then re-added the platform to let firebasex/androidx install androix-adapter by itself, getting the same error

`cordova-plugin-androidx-adapter: EXCEPTION: Failed to load dependencies: Error: Cannot find module recursive-readdir`

npm 6.10.3
node 10.15.0
9.0.0 (cordova-lib@9.0.1)

**Comment by globules-io** [comment]
Turns out after a few add/remove platform, it worked.
Cordova is broken.

**Comment by pushparajsamant** [comment]
Just readding the plugin and removing/adding the platform worked for me
